name:                ap-haskell

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ap-haskell#readme>

dependencies:
- base
- tasty            # The test framework tasty
- tasty-hunit      # unit-testing with tasty
- QuickCheck       # property-based testing

library:
  source-dirs: src

executables:
  ap-haskell: # selve navnet
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ap-haskell

tests:
  ap-haskell-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ap-haskell
